name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert Markdown to LaTeX
        uses: docker://pandoc/latex:2.17.1
        with:
          args: >-
            --from markdown
            --to beamer
            --standalone
            --output 04-functions.tex
            fundamentals/04-functions.md

      - name: Render LaTeX
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: 04-functions.tex

