name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Create file list
        id: files
        run: echo "::set-output name=files::$(printf '"%s" ' **/*.md)"

      - name: Render Markdown
        uses: docker://pandoc/latex:2.19
        with:
          args: --output=result.pdf ${{ steps.files_list.outputs.files }}

      - name: Prepare artifacts
        run: mkdir -p _site && mv result.pdf _site/

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
